// Lege Test User an
###
# @name loginInfo
POST http://localhost:8080/user
Content-Type: application/json

{
    "userName": "Mr.Specter"
}

###
@token = {{loginInfo.response.headers.Authorization}}

// Lege Lobby an
###
POST http://localhost:8080/lobby
Content-Type: application/json
Authorization: {{token}}

{
    "creator": "636ab63d04695ec920d339aa",
    "gamemode": "Dis a gamemode"
}

//Get Lobby
###
GET http://localhost:8080/lobby/636d44139f17922d1086bddc
Authorization: {{token}}

// Update Lobby
###
PUT http://localhost:8080/lobby/636ab6b8607558e98c5f87d0
Content-Type: application/json

{
    "creator": "636ab63d04695ec920d339aa",
    "gamemode": "A gamemode"
}

// Delete Lobby
###
DELETE http://localhost:8080/lobby/636ab6b8607558e98c5f87d0
Content-Type: application/json