// Lege Test User an
###
# @name loginInfo
POST http://localhost:8080/user
Content-Type: application/json

{
    "name": "Mr.Specter"
}

###
@token = {{loginInfo.response.headers.Authorization}}

// Lege Lobby an
###
# @name lobbyInfo
POST http://localhost:8080/lobby
Content-Type: application/json
Authorization: {{token}}

{
    "gamemode": "Dis a gamemode"
}
###
@lobbyId = {{lobbyInfo.response.body._id}}

//Get Lobby
###
GET http://localhost:8080/lobby/{{lobbyId}}
Authorization: {{token}}

//LEAVE Lobby
###
GET http://localhost:8080/lobby/{{lobbyId}}/leave
Authorization: {{token}}

//LEAVE Lobby error
###
GET http://localhost:8080/lobby/{{lobbyId}}/leave
Authorization: {{token}}


// Update Lobby
###
PUT http://localhost:8080/lobby/{{lobbyId}}
Content-Type: application/json

{
    "creator": "636ab63d04695ec920d339aa",
    "gamemode": "A gamemode"
}

// Delete Lobby
###
DELETE http://localhost:8080/lobby/{{lobbyId}}
Content-Type: application/json